### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by TheTommyTwitch**
Hey I really wanted to contribute with some docs! It's not finished. Hope you don't mind :)

### CODE REVIEW

**Comment by DerFlatulator** [comment]
Hi. I probably should have communicated this clearer, but the JS files in `/examples/docs/` actually are already documentation, they are passed through [docco](https://jashkenas.github.io/docco/) and available for viewing here:
https://derflatulator.github.io/haloapi.js/docco/haloapi.html

(`filename.js` gets converted to `/docco/filename.html` on that domain)

**Comment by DerFlatulator** [comment]
If you'd like to help flesh out that documentation page or add other examples, which would be awesome, feel free to send a fresh pull request (that JS file has since changed slightly) with new additions.

**Comment by TheTommyTwitch** [comment]
I will try to add some new examples to the js file.

**Comment by DerFlatulator** [comment]
Awesome! 
If you just want to push the JS file, that's easy. Otherwise you have the option of building and pushing the docs branch, which is a bit more complex. see for more info:
https://github.com/DerFlatulator/haloapi.js#development

**Pull request closed without merging**
